sonar.projectKey=Hospital-Appointment-System
sonar.organization=YOUR_ORG_NAME

sonar.sources=src,include
sonar.tests=tests

sonar.sourceEncoding=UTF-8

# C++ settings
sonar.cfamily.build-wrapper-output=build_wrapper_output_directory
